#!/usr/bin/env bash
# Configure server to listen on port 80

sudo fuser -k 80/tcp

sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default


sudo service nginx restart

