#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".
i=0
while [[ $i -lt 1 ]]
do
	j=0
	while [[ $j -lt 9 ]]
	do
		echo "Best School"
		j=$(expr $j + 1)
		done
	if [[ $i -eq 0 ]]
	then
		echo "Hi"
	fi
	i=$(expr $i + 1)
	echo "Best School"
done
